### ISSUE TITLE
Project does not compile with gcc 5

### ISSUE THREAD

**Issue by simonjantsch** [hguenther/vvt#10]
When compiling the entire project (stack clean; stack build) with gcc 5.3.1 linking with bindings-llvm does not work. Following error appears
![vvtgccerror](https://cloud.githubusercontent.com/assets/13819379/16614154/d1af7564-436f-11e6-93a2-0510aecf3f47.png)

Compiling with gcc version 4.9.3 works. When bindings-llvm is already compiled, only compiling vvt with gcc 5.3.1 works too.

**Comment by simonjantsch** [comment]
I suspect this has to do with following bug: https://llvm.org/bugs/show_bug.cgi?id=23529

**Comment by hgoes** [comment]
Can you run the bindings-llvm test-suite and see if the same bug happens? You can run it by using "cabal test".

**Comment by simonjantsch** [comment]
I tried and it has the same issue with gcc version 5.

**Comment by hgoes** [comment]
It looks like there isn't anything we can do on our end to fix this. Let's hope this gets resolved upstream...
