### ISSUE TITLE
Too fast verification run?

### ISSUE THREAD

**Issue by alaarman** [hguenther/vvt#11]
Verification of the following simple example succeeds with only one level. Debugging the backends doesn ot show the consecution calls one would expect to derive the necessary invariant.
Does VVT perhaps simplify this example too much?

[dfa.l.zip](https://github.com/hguenther/vvt/files/357786/dfa.l.zip)
[dfa.c.zip](https://github.com/hguenther/vvt/files/357787/dfa.c.zip)
(I've skipped the large-block reduction and the transition relation optimizing steps. The latter solves the problem already.)

**Comment by simonjantsch** [comment]
When encoding the .c file with `vvt encode -o dfa.l dfa.c` I get following transition relation:
[dfa.l.zip](https://github.com/hguenther/vvt/files/359907/dfa.l.zip)
Verifying with `vvt-verify < dfa.l` yields a runtime of ca 10 seconds and the run seems reasonable, I didnt look at the program and fixpoint in detail though. Is this the result you had aswell? Can you specify how you built the transition relation? This is the log I get with the verify run, in the end the fixpoint is printed:
[log.txt](https://github.com/hguenther/vvt/files/359919/log.txt)

**Comment by hgoes** [comment]
I get the same results as @simonjantsch. @alaarman, can you give the exact commands that produces your dfa.l file?

**Comment by hgoes** [comment]
Since we had some in-person discussions about it, it seems to be resolved.
