### ISSUE TITLE
mathsat error: "model generation not enabled"

### ISSUE THREAD

**Issue by simonjantsch** [hguenther/vvt#3]
Mathsat gives the error `(error "model generation not enabled")` although `setOption (ProduceModels True)` was called when the SMTPool was created. 

The SMTPool is created in the function `runIC3` in the file CTIGAR.hs, line 340. The error occurs when adding 

``` haskell
curSt <- getValues (interpCur st) >>= TR.renderState (ic3Model cfg)
curInpSt <- getValues (interpInputs st) >>= TR.renderInput (ic3Model cfg)
nxtSt <- getValues (interpNxt st) >>= TR.renderState (ic3Model cfg)
liftIO $ putStrLn $ "State:\n"++curSt++"\nInput:\n"++curInpSt++"\nNext state:\n"++nxtSt                 
```

in `interpolateState` (line 1124).

**Comment by hgoes** [comment]
This actually works as indented:
The interpolation query must be performed on an unsatisfiable instance, thus there is no generated model. The error message is misleading, but since it's coming from MathSAT, there isn't much I can do about it.
